-- Reusable user-defined prompt templates ("transformations") that run over
-- a raw material's extracted text and persist the LLM output as an artifact
-- on the knowledge base. Templates can be flagged apply_default so the
-- ingestion pipeline runs them automatically once a raw material reaches
-- the completed state. Manual / agent-tool runs are also supported.

CREATE TABLE IF NOT EXISTS mate_wiki_transformation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kb_id BIGINT,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    name VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    prompt_template TEXT NOT NULL,
    apply_default BOOLEAN NOT NULL DEFAULT FALSE,
    model_id BIGINT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_wtr_kb ON mate_wiki_transformation (kb_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wtr_ws ON mate_wiki_transformation (workspace_id, deleted);

DROP TRIGGER IF EXISTS trg_mate_wiki_transformation_upd_ts ON mate_wiki_transformation;
CREATE TRIGGER trg_mate_wiki_transformation_upd_ts BEFORE UPDATE ON mate_wiki_transformation
    FOR EACH ROW EXECUTE FUNCTION set_update_time();

CREATE UNIQUE INDEX IF NOT EXISTS uk_wtr_kb_name ON mate_wiki_transformation (kb_id, name, deleted);

CREATE TABLE IF NOT EXISTS mate_wiki_transformation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    transformation_id BIGINT NOT NULL,
    kb_id BIGINT NOT NULL,
    workspace_id BIGINT NOT NULL DEFAULT 1,
    input_kind VARCHAR(16) NOT NULL,
    raw_id BIGINT,
    page_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    output TEXT,
    error VARCHAR(2048),
    model_id BIGINT,
    triggered_by VARCHAR(32) NOT NULL DEFAULT 'manual',
    started_at TIMESTAMP(3),
    completed_at TIMESTAMP(3),
    duration_ms BIGINT,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_wtrn_tr ON mate_wiki_transformation_run (transformation_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wtrn_kb ON mate_wiki_transformation_run (kb_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wtrn_raw ON mate_wiki_transformation_run (raw_id, deleted);

DROP TRIGGER IF EXISTS trg_mate_wiki_transformation_run_upd_ts ON mate_wiki_transformation_run;
CREATE TRIGGER trg_mate_wiki_transformation_run_upd_ts BEFORE UPDATE ON mate_wiki_transformation_run
    FOR EACH ROW EXECUTE FUNCTION set_update_time();
