CREATE TABLE IF NOT EXISTS mate_wiki_processing_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kb_id BIGINT NOT NULL,
    raw_id BIGINT NOT NULL,
    job_type VARCHAR(32) NOT NULL DEFAULT 'heavy_ingest',
    stage VARCHAR(64) NOT NULL DEFAULT 'queued',
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    primary_model_id BIGINT,
    current_model_id BIGINT,
    fallback_chain_json TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    error_code VARCHAR(64),
    error_message TEXT,
    resume_from_stage VARCHAR(64),
    meta_json TEXT,
    started_at TIMESTAMP(3),
    finished_at TIMESTAMP(3),
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_wpj_raw ON mate_wiki_processing_job (raw_id);

CREATE INDEX IF NOT EXISTS idx_wpj_status ON mate_wiki_processing_job (status);

CREATE INDEX IF NOT EXISTS idx_wpj_kb ON mate_wiki_processing_job (kb_id, status);

-- 模拟 MySQL ON UPDATE CURRENT_TIMESTAMP：应用未显式改动 update_time 时自动刷新
CREATE OR REPLACE FUNCTION set_update_time() RETURNS trigger AS $$
BEGIN
    IF NEW.update_time IS NULL OR NEW.update_time = OLD.update_time THEN
        NEW.update_time := CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_mate_wiki_processing_job_upd_ts ON mate_wiki_processing_job;
CREATE TRIGGER trg_mate_wiki_processing_job_upd_ts BEFORE UPDATE ON mate_wiki_processing_job
    FOR EACH ROW EXECUTE FUNCTION set_update_time();
