CREATE TABLE IF NOT EXISTS mate_skill_usage_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    skill_name VARCHAR(128) NOT NULL,
    skill_id BIGINT,
    agent_id BIGINT NOT NULL DEFAULT 0,
    conversation_id VARCHAR(128) NOT NULL DEFAULT '',
    load_count BIGINT NOT NULL DEFAULT 0,
    last_loaded_at TIMESTAMP(3),
    last_file_path VARCHAR(512),
    last_token_estimate INTEGER,
    create_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_skill_usage_scope ON mate_skill_usage_stat (skill_name, agent_id, conversation_id);

CREATE INDEX IF NOT EXISTS idx_skill_usage_agent_recent ON mate_skill_usage_stat (agent_id, last_loaded_at);

CREATE INDEX IF NOT EXISTS idx_skill_usage_name_recent ON mate_skill_usage_stat (skill_name, last_loaded_at);

DROP TRIGGER IF EXISTS trg_mate_skill_usage_stat_upd_ts ON mate_skill_usage_stat;
CREATE TRIGGER trg_mate_skill_usage_stat_upd_ts BEFORE UPDATE ON mate_skill_usage_stat
    FOR EACH ROW EXECUTE FUNCTION set_update_time();
